---
# tasks file for roles/pi_hole
- name: Check if project directory exists
  ansible.builtin.stat:
    path: "{{ pihole_project_dir }}"
  register: project_dir

- name: Create project directory
  ansible.builtin.file:
    path: "{{ pihole_project_dir }}"
    state: directory
    recurse: true
    mode: "755"
  when: not project_dir.stat.exists

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ pihole_project_dir }}/docker-compose.yml"
    mode: "644"

- name: Start Pi-hole
  community.docker.docker_compose:
    project_src: "{{ pihole_project_dir }}"
    state: present
