galaxy_info:
  author: Tim Adler
  description: Deploy single-node Victoria Metrics as a Docker container.
  license: MIT
  min_ansible_version: "2.1"
  galaxy_tags:
    - monitoring
    - victoriametrics
    - docker

dependencies: []
